server:
  port: 8893  #服务端口
spring:
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML5
  application:
    name: user-consumer   #服务名
eureka:
  client:
    service-url:
      defaultZone: http://@localhost:8500/eureka/  #服务注册地址
  instance:
    hostname: localhost
thymeleaf:
  cache: false      #关闭缓存
  prefix: classpath:/template/
  suffix: .html
  encoding: UTF-8
feign:
   hystrix:
     enabled: true