server:
  port: 8896
spring:
  application:
    name: b2b-goods-consumer
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8500/eureka/
  instance:
      hostname: localhost
feign:
  hystrix:
    enabled: true


